"""Extract translatable strings into `src/astrodoro/i18n/astrodoro.pot`.

A small `xgettext` replacement: it walks the AST looking for calls to `_()`,
`gettext()` and `ngettext()` with literal arguments, which is the only form the
project uses. Keeping it in Python means contributors need no system gettext.

    python scripts/extract_messages.py            # rewrite the .pot
    python scripts/extract_messages.py --check    # fail if the .pot is stale

The `.po` files are not touched: merging new messages into a translation is a
translator's decision. `--missing pt_BR` lists what a catalogue still lacks.
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src" / "astrodoro"
POT = SOURCE / "i18n" / "astrodoro.pot"
FUNCS = {"_", "N_", "gettext", "ngettext"}

HEADER = '''# Translation template for Astrodoro.
# Generated by scripts/extract_messages.py — do not edit by hand.
msgid ""
msgstr ""
"Project-Id-Version: astrodoro\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\\n"

'''


def _name(node: ast.AST) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return None


def _literal(node: ast.AST) -> str | None:
    """A string literal, including implicit concatenation across lines."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        left, right = _literal(node.left), _literal(node.right)
        return None if left is None or right is None else left + right
    return None


def collect() -> dict[str, list[str]]:
    """message -> sorted list of "file:line" references."""
    found: dict[str, set[str]] = {}
    for path in sorted(SOURCE.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        rel = path.relative_to(ROOT).as_posix()
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call) or _name(node.func) not in FUNCS:
                continue
            if not node.args:
                continue
            msg = _literal(node.args[0])
            if msg:
                found.setdefault(msg, set()).add(f"{rel}:{node.lineno}")
    return {k: sorted(v) for k, v in sorted(found.items())}


def escape(s: str) -> str:
    return (s.replace("\\", "\\\\").replace('"', '\\"')
            .replace("\n", "\\n").replace("\t", "\\t"))


def render(messages: dict[str, list[str]]) -> str:
    out = [HEADER]
    for msg, refs in messages.items():
        out.append("#: " + " ".join(refs) + "\n")
        out.append(f'msgid "{escape(msg)}"\n')
        out.append('msgstr ""\n\n')
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the .pot is out of date")
    ap.add_argument("--missing", metavar="LANG",
                    help="list messages a catalogue does not translate yet")
    args = ap.parse_args()

    messages = collect()
    text = render(messages)

    if args.missing:
        sys.path.insert(0, str(ROOT / "src"))
        from astrodoro.i18n import LOCALE_DIR, _parse_po
        po = LOCALE_DIR / args.missing / "LC_MESSAGES" / "astrodoro.po"
        if not po.exists():
            print(f"no catalogue at {po}")
            return 1
        catalog = _parse_po(po)
        missing = [m for m in messages
                   if not (catalog.get(m) or "").strip()]
        extra = [m for m in catalog if m not in messages]
        for m in missing:
            print("missing:", m.replace("\n", "\\n")[:100])
        for m in extra:
            print("stale:  ", m.replace("\n", "\\n")[:100])
        print(f"\n{len(messages) - len(missing)}/{len(messages)} translated, "
              f"{len(extra)} stale")
        return 1 if missing or extra else 0

    if args.check:
        current = POT.read_text(encoding="utf-8") if POT.exists() else ""
        if current != text:
            print(f"{POT} is out of date — run: "
                  f"python scripts/extract_messages.py")
            return 1
        print(f"{POT} is up to date ({len(messages)} messages)")
        return 0

    POT.parent.mkdir(parents=True, exist_ok=True)
    POT.write_text(text, encoding="utf-8")
    print(f"{len(messages)} messages -> {POT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
