"""Build `build/Astrodoro.app`, so macOS stops calling the program "python3.14".

Setting the Qt application name fixes what Qt itself reports, but the Dock, the
menu bar and Activity Monitor read the name from a bundle's `Info.plist`. A bare
interpreter has no bundle, so macOS falls back to the executable's name.

The bundle is generated rather than committed: its launcher holds the absolute
path of this checkout's virtualenv.

    python scripts/make_app.py        # build/Astrodoro.app
    open build/Astrodoro.app          # or drag it to /Applications
"""
from __future__ import annotations

import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from astrodoro import __version__  # noqa: E402
from astrodoro.ui.branding import GLYPH_MAX, PLATE  # noqa: E402

APP_NAME = "Astrodoro"
BUNDLE_ID = "com.github.mathmed.astrodoro"
OUT = ROOT / "build" / f"{APP_NAME}.app"
PLATE_MASTER = ROOT / "assets" / "icon-app.png"

#: The slots `iconutil` expects, as (file name, pixel size).
ICONSET = [
    ("icon_16x16.png", 16), ("icon_16x16@2x.png", 32),
    ("icon_32x32.png", 32), ("icon_32x32@2x.png", 64),
    ("icon_128x128.png", 128), ("icon_128x128@2x.png", 256),
    ("icon_256x256.png", 256), ("icon_256x256@2x.png", 512),
    ("icon_512x512.png", 512), ("icon_512x512@2x.png", 1024),
]


def build_icns(dest: Path) -> bool:
    """Write Astrodoro.icns, taking each size from whichever drawing suits it.

    The same rule as `ui/branding.py`, and it reads `GLYPH_MAX` from there so
    the two cannot drift: the engraved plate below about 48 px collapses into
    flat grey, so the small slots come from the stroke glyph instead.
    """
    if not shutil.which("iconutil"):
        print("  iconutil not found — skipping the .icns (macOS only)")
        return False

    from PySide6.QtCore import QSize, Qt
    from PySide6.QtGui import QGuiApplication, QPixmap

    from astrodoro.ui import icons

    app = QGuiApplication.instance() or QGuiApplication([])
    plate = QPixmap(str(PLATE_MASTER if PLATE_MASTER.exists() else PLATE))
    if plate.isNull():
        print(f"  no plate at {PLATE_MASTER} — run scripts/derive_brand.py")
        return False

    iconset = dest.parent / f"{APP_NAME}.iconset"
    if iconset.exists():
        shutil.rmtree(iconset)
    iconset.mkdir(parents=True)
    for name, px in ICONSET:
        if px <= GLYPH_MAX:
            icons.pixmap("mark", "#dcdfe4", px).save(str(iconset / name))
        else:
            plate.scaled(QSize(px, px), Qt.KeepAspectRatio,
                         Qt.SmoothTransformation).save(str(iconset / name))
    subprocess.run(["iconutil", "-c", "icns", str(iconset),
                    "-o", str(dest)], check=True)
    shutil.rmtree(iconset)
    del app
    return True


def main() -> None:
    if sys.platform != "darwin":
        sys.exit("this builds a macOS .app bundle; nothing to do elsewhere")

    launcher = ROOT / ".venv" / "bin" / "astrodoro-gui"
    if not launcher.exists():
        sys.exit(f"{launcher} missing — run: uv pip install -e .")

    if OUT.exists():
        shutil.rmtree(OUT)
    macos = OUT / "Contents" / "MacOS"
    resources = OUT / "Contents" / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    has_icon = build_icns(resources / f"{APP_NAME}.icns")

    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": APP_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": __version__,
        "CFBundleVersion": __version__,
        "LSMinimumSystemVersion": "12.0",
        # Without this the whole interface is drawn at 1x and then upscaled.
        "NSHighResolutionCapable": True,
        "LSApplicationCategoryType": "public.app-category.education",
        # The program talks to a USB camera and serves a page to a phone on the
        # local network; macOS asks the user once, and only if these are here.
        "NSCameraUsageDescription":
            f"{APP_NAME} reads frames from your astronomy camera.",
        "NSLocalNetworkUsageDescription":
            f"{APP_NAME} serves the handset page to your phone over the "
            f"local network.",
    }
    if has_icon:
        info["CFBundleIconFile"] = f"{APP_NAME}.icns"
    (OUT / "Contents" / "Info.plist").write_bytes(plistlib.dumps(info))

    shim = macos / APP_NAME
    shim.write_text(
        "#!/bin/sh\n"
        "# Generated by scripts/make_app.py — do not edit.\n"
        f'exec "{launcher}" "$@"\n'
    )
    shim.chmod(0o755)

    print(f"{OUT.relative_to(ROOT)}")
    print(f"  name    {APP_NAME}  (was the interpreter's name)")
    print(f"  version {__version__}")
    print(f"  icon    {'Astrodoro.icns' if has_icon else 'none'}")
    print(f"  runs    {launcher.relative_to(ROOT)}")
    print("\nopen it with:  open build/Astrodoro.app")


if __name__ == "__main__":
    main()
